name: Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode
      shell: bash
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --parallel
